version: '3'

services:

     webservergo:
         build: .
         ports: 
             - 8088:8080


     nginx:
         image: nginx
         volumes: 
             - ./nginx:/usr/share/nginx/html
         ports:
             - 8080:80

     redis: 
        image: redis:alpine
        expose: 
             - 6379
             